# Type Name                  ID GECOS                           Home Shell
g tinypirelay-control        -  -                               -    -
u tinypirelay-media          -  "TinyPiRelay media service"   /    /usr/sbin/nologin
u tinypirelay-web            -  "TinyPiRelay web service"     /    /usr/sbin/nologin
m tinypirelay-media          tinypirelay-control
m tinypirelay-media          audio
m tinypirelay-web            tinypirelay-control
