from __future__ import annotations

import contextlib
import io
import json
import os
import sys
import tempfile
import unittest
from pathlib import Path
from types import SimpleNamespace
from unittest import mock


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from tinypirelay import probe  # noqa: E402


FIXTURES = Path(__file__).parent / "fixtures" / "probe"


def fixture(name: str) -> str:
    return (FIXTURES / name).read_text(encoding="utf-8")


class FakeRunner:
    def __init__(self, responses: dict[tuple[str, ...], probe.CommandResult]):
        self.responses = responses
        self.calls: list[tuple[str, ...]] = []

    def __call__(self, argv: object) -> probe.CommandResult:
        key = tuple(argv)  # type: ignore[arg-type]
        self.calls.append(key)
        return self.responses.get(key, probe.CommandResult(None, error="command not found"))


def complete_runner(*, missing_element: str | None = None) -> FakeRunner:
    listing = fixture("gst-inspect-list")
    if missing_element:
        listing = "\n".join(
            line
            for line in listing.splitlines()
            if ":" not in line
            or line.split(":", 2)[1].strip() != missing_element
        )
    responses = {
            ("getconf", "LONG_BIT"): probe.CommandResult(0, "32\n"),
            ("dpkg", "--print-architecture"): probe.CommandResult(0, "armhf\n"),
            ("arecord", "-l"): probe.CommandResult(0, fixture("arecord-usb")),
            ("apt-cache", "policy", *probe.APT_PACKAGES): probe.CommandResult(
                0, fixture("apt-policy-bookworm")
            ),
            ("gst-launch-1.0", "--version"): probe.CommandResult(
                0, "gst-launch-1.0 version 1.22.0\nGStreamer 1.22.0\n"
            ),
            ("gst-inspect-1.0", "--version"): probe.CommandResult(
                0, "gst-inspect-1.0 version 1.22.0\nGStreamer 1.22.0\n"
            ),
            ("gst-inspect-1.0",): probe.CommandResult(0, listing),
        }
    plugins = set(probe.parse_gst_element_list(listing).values())
    details_fixture = fixture("gst-plugin-details")
    for plugin in plugins:
        responses[("gst-inspect-1.0", plugin)] = probe.CommandResult(
            0, details_fixture.replace("coreelements", plugin)
        )
    return FakeRunner(responses)


def pi_files() -> dict[str, bytes]:
    return {
        "/etc/os-release": fixture("os-release-bookworm").encode(),
        "/proc/cpuinfo": fixture("cpuinfo-zero-w").encode(),
        "/proc/meminfo": fixture("meminfo-zero-w").encode(),
        "/proc/device-tree/model": b"Raspberry Pi Zero W Rev 1.1\x00",
    }


def collect_pi(runner: FakeRunner | None = None) -> dict[str, object]:
    files = pi_files()
    return probe.collect_probe(
        runner=runner or complete_runner(),
        reader=files.get,
        disk_usage_fn=lambda _path: (16 * 1024**3, 4 * 1024**3, 12 * 1024**3),
        uname_fn=lambda: SimpleNamespace(
            system="Linux",
            node="tinypi",
            release="6.1.21+",
            version="#1642 PREEMPT",
            machine="armv6l",
            processor="",
        ),
        cpu_count_fn=lambda: 1,
        pointer_bits=32,
    )


def collect_complete_platform(
    os_release: str,
    *,
    machine: str,
    bits: int,
    architecture: str,
    rpi_issue: bool = False,
) -> dict[str, object]:
    runner = complete_runner()
    runner.responses[("getconf", "LONG_BIT")] = probe.CommandResult(0, f"{bits}\n")
    runner.responses[("dpkg", "--print-architecture")] = probe.CommandResult(
        0, f"{architecture}\n"
    )
    files = pi_files()
    files["/etc/os-release"] = os_release.encode()
    if rpi_issue:
        files["/etc/rpi-issue"] = b"Raspberry Pi reference image generated by pi-gen\n"
    if machine in {"aarch64", "arm64"}:
        files["/proc/cpuinfo"] = (
            b"processor : 0\nmodel name : ARMv8 Processor\nHardware : BCM2711\n"
            b"Revision : c03111\n"
        )
        files["/proc/device-tree/model"] = b"Raspberry Pi 4 Model B Rev 1.1\x00"
    return probe.collect_probe(
        runner=runner,
        reader=files.get,
        disk_usage_fn=lambda _path: (100, 20, 80),
        uname_fn=lambda: SimpleNamespace(
            system="Linux", release="6.1", machine=machine, processor=""
        ),
        cpu_count_fn=lambda: 1,
        pointer_bits=bits,
    )


class ParserTests(unittest.TestCase):
    def test_parses_os_release_quotes_and_normalizes_values(self) -> None:
        values = probe.parse_os_release(fixture("os-release-bookworm"))
        self.assertEqual(values["ID"], "raspbian")
        self.assertEqual(values["VERSION_ID"], "12")
        self.assertEqual(values["PRETTY_NAME"], "Raspbian GNU/Linux 12 (bookworm)")

    def test_parses_zero_w_cpu_and_memory(self) -> None:
        cpu = probe.parse_cpuinfo(fixture("cpuinfo-zero-w"))
        memory = probe.parse_meminfo(fixture("meminfo-zero-w"))
        self.assertEqual(cpu["model"], "ARMv6-compatible processor rev 7 (v6l)")
        self.assertEqual(cpu["hardware"], "BCM2835")
        self.assertEqual(cpu["revision"], "9000c1")
        self.assertEqual(cpu["logical_cpus"], 1)
        self.assertEqual(memory["total_bytes"], 444564 * 1024)

    def test_parses_modern_pi_cpuinfo_model(self) -> None:
        cpu = probe.parse_cpuinfo(
            "processor : 0\n\nprocessor : 1\n\n"
            "Revision : d03114\nModel : Raspberry Pi 4 Model B Rev 1.4\n"
        )
        self.assertEqual(cpu["model"], "Raspberry Pi 4 Model B Rev 1.4")
        self.assertEqual(cpu["logical_cpus"], 2)

    def test_parses_and_normalizes_alsa_hardware_ids(self) -> None:
        devices = probe.parse_arecord_devices(fixture("arecord-usb"))
        self.assertEqual([item["alsa_id"] for item in devices], ["hw:1,0", "hw:2,1"])
        self.assertEqual(devices[0]["card_name"], "USB Audio Device")
        self.assertEqual(devices[1]["device_name"], "HiFi Capture")

    def test_parses_apt_candidate_and_architecture_qualified_heading(self) -> None:
        packages = probe.parse_apt_policy(fixture("apt-policy-bookworm"))
        self.assertEqual(packages["python3"]["installed_version"], "3.11.2-1+b1")
        self.assertIsNone(packages["gstreamer1.0-plugins-bad"]["installed_version"])
        self.assertEqual(
            packages["gstreamer1.0-plugins-bad"]["candidate_version"],
            "1.22.0-4+deb12u6",
        )

    def test_parses_gstreamer_element_listing(self) -> None:
        elements = probe.parse_gst_element_list(fixture("gst-inspect-list"))
        self.assertEqual(elements["alsasrc"], "alsa")
        self.assertEqual(elements["matroskamux"], "matroska")
        self.assertEqual(elements["srtsink"], "srt")
        self.assertEqual(elements["valve"], "coreelements")
        self.assertNotIn("count", elements)

    def test_parses_gstreamer_plugin_version(self) -> None:
        details = probe.parse_gst_plugin_details(fixture("gst-plugin-details"))
        self.assertEqual(details, {"name": "coreelements", "version": "1.22.0"})


class CollectionTests(unittest.TestCase):
    def test_collects_complete_pi_fixture_with_stable_tri_state_schema(self) -> None:
        runner = complete_runner()
        result = collect_pi(runner)

        self.assertEqual(result["schema_version"], 1)
        self.assertEqual(result["status"], probe.PRESENT)
        self.assertEqual(result["actions"], [])
        self.assertEqual(result["platform"]["os_release"]["version_codename"], "bookworm")
        self.assertEqual(result["platform"]["kernel"]["machine"], "armv6l")
        self.assertEqual(result["platform"]["userland_bitness"]["bits"], 32)
        self.assertEqual(
            result["platform"]["userland_bitness"]["method"], "getconf_LONG_BIT"
        )
        self.assertEqual(result["platform"]["dpkg_architecture"]["value"], "armhf")
        self.assertEqual(result["hardware"]["board"]["revision"], "9000c1")
        self.assertEqual(result["hardware"]["memory"]["total_bytes"], 444564 * 1024)
        self.assertEqual(len(result["audio"]["capture_devices"]), 2)
        self.assertTrue(result["packages"]["items"]["python3"]["installed"])
        self.assertFalse(
            result["packages"]["items"]["gstreamer1.0-plugins-bad"]["installed"]
        )
        self.assertEqual(result["gstreamer"]["required_elements"]["srtsink"]["plugin"], "srt")
        self.assertEqual(
            result["gstreamer"]["required_elements"]["srtsink"]["plugin_version"],
            "1.22.0",
        )
        valve = result["gstreamer"]["required_elements"]["valve"]
        self.assertEqual("coreelements", valve["plugin"])
        self.assertEqual("1.22.0", valve["plugin_version"])
        self.assertEqual("libgstreamer1.0-0", probe.ELEMENT_PACKAGES["valve"])
        self.assertEqual("libgstreamer1.0-0", probe.ELEMENT_PACKAGES["filesink"])
        for element in ("matroskamux", "opusparse", "filesink", "fakesink"):
            self.assertEqual(
                probe.PRESENT,
                result["gstreamer"]["required_elements"][element]["status"],
            )
        self.assertIn(("gst-inspect-1.0",), runner.calls)

        statuses: list[str] = []

        def gather(value: object) -> None:
            if isinstance(value, dict):
                if "status" in value:
                    statuses.append(value["status"])
                for child in value.values():
                    gather(child)
            elif isinstance(value, list):
                for child in value:
                    gather(child)

        gather(result)
        self.assertTrue(statuses)
        self.assertLessEqual(set(statuses), {probe.PRESENT, probe.MISSING, probe.UNVERIFIED})

    def test_complete_unsupported_os_or_architecture_fails_platform_gate(self) -> None:
        cases = (
            (
                "unsupported OS",
                'ID=ubuntu\nNAME="Ubuntu"\nVERSION_ID="24.04"\n'
                "VERSION_CODENAME=bookworm\n",
                "armv6l",
                32,
                "armhf",
                "OS ID 'ubuntu'",
            ),
            (
                "unsupported architecture",
                fixture("os-release-bookworm"),
                "x86_64",
                64,
                "amd64",
                "dpkg architecture/userland amd64/64-bit",
            ),
            (
                "unmarked Debian ARM host",
                'ID=debian\nNAME="Debian GNU/Linux"\nVERSION_ID="12"\n'
                "VERSION_CODENAME=bookworm\n",
                "aarch64",
                64,
                "arm64",
                "no Raspberry Pi OS identity marker",
            ),
        )
        for name, os_release, machine, bits, architecture, reason in cases:
            with self.subTest(name):
                result = collect_complete_platform(
                    os_release,
                    machine=machine,
                    bits=bits,
                    architecture=architecture,
                )
                baseline = result["platform"]["os_architecture_baseline"]
                self.assertEqual(baseline["status"], probe.MISSING)
                self.assertIn(reason, baseline["reason"])
                self.assertEqual(result["status"], probe.MISSING)
                self.assertTrue(
                    all(
                        result["platform"][key]["status"] == probe.PRESENT
                        for key in (
                            "os_release",
                            "kernel",
                            "userland_bitness",
                            "dpkg_architecture",
                        )
                    )
                )
                self.assertTrue(
                    all(
                        result[key]["status"] == probe.PRESENT
                        for key in ("hardware", "storage", "audio", "packages", "gstreamer")
                    )
                )
                self.assertTrue(
                    any(
                        "supported OS/architecture baseline" in action
                        for action in result["actions"]
                    )
                )

    def test_complete_64_bit_raspberry_pi_os_baseline_is_present(self) -> None:
        result = collect_complete_platform(
            'ID=debian\nNAME="Debian GNU/Linux"\nVERSION_ID="12"\n'
            "VERSION_CODENAME=bookworm\n",
            machine="aarch64",
            bits=64,
            architecture="arm64",
            rpi_issue=True,
        )
        self.assertEqual(
            result["platform"]["os_architecture_baseline"]["status"],
            probe.PRESENT,
        )
        self.assertEqual(result["status"], probe.PRESENT)

    def test_missing_element_fails_closed_and_names_package_action(self) -> None:
        result = collect_pi(complete_runner(missing_element="srtsink"))
        self.assertEqual(result["status"], probe.MISSING)
        self.assertEqual(
            result["gstreamer"]["required_elements"]["srtsink"]["status"], probe.MISSING
        )
        self.assertTrue(
            any(
                "gstreamer1.0-plugins-bad (srtsink)" in action
                for action in result["actions"]
            )
        )

    def test_missing_valve_names_core_package_action(self) -> None:
        result = collect_pi(complete_runner(missing_element="valve"))
        self.assertEqual(result["status"], probe.MISSING)
        self.assertEqual(
            probe.MISSING,
            result["gstreamer"]["required_elements"]["valve"]["status"],
        )
        self.assertTrue(
            any("libgstreamer1.0-0 (valve)" in action for action in result["actions"])
        )

    def test_no_audio_is_missing_but_absent_inspector_leaves_elements_unverified(self) -> None:
        runner = FakeRunner(
            {
                ("dpkg", "--print-architecture"): probe.CommandResult(0, "arm64\n"),
                ("arecord", "-l"): probe.CommandResult(
                    1, stderr="arecord: device_list:274: no soundcards found...\n"
                ),
            }
        )
        result = probe.collect_probe(
            runner=runner,
            reader=lambda _path: None,
            disk_usage_fn=lambda _path: (100, 50, 50),
            uname_fn=lambda: SimpleNamespace(
                system="Windows",
                node="dev",
                release="10",
                version="build",
                machine="AMD64",
                processor="AMD64",
            ),
            cpu_count_fn=lambda: 8,
            pointer_bits=64,
        )
        self.assertEqual(result["audio"]["status"], probe.MISSING)
        self.assertEqual(
            result["platform"]["userland_bitness"]["status"], probe.UNVERIFIED
        )
        self.assertEqual(
            result["platform"]["userland_bitness"]["method"],
            "python_pointer_size_fallback",
        )
        self.assertIn("Run `getconf LONG_BIT` to verify userland bitness.", result["actions"])
        round_tripped = json.loads(probe.render_json(result))
        self.assertEqual(result["actions"], probe._actions(round_tripped))
        self.assertEqual(result["gstreamer"]["tools"]["gst-inspect-1.0"]["status"], probe.MISSING)
        self.assertEqual(
            result["gstreamer"]["required_elements"]["alsasrc"]["status"],
            probe.UNVERIFIED,
        )
        self.assertIn("Connect or enable an ALSA capture device", probe.render_human(result))

    def test_device_tree_binary_revision_is_normalized(self) -> None:
        files = pi_files()
        files["/proc/cpuinfo"] = b"processor : 0\nmodel name : ARMv7 Processor\n"
        files["/sys/firmware/devicetree/base/system/linux,revision"] = bytes.fromhex(
            "00a02082"
        )
        result = probe.collect_probe(
            runner=complete_runner(),
            reader=files.get,
            disk_usage_fn=lambda _path: (100, 20, 80),
            uname_fn=lambda: SimpleNamespace(
                system="Linux",
                node="pi",
                release="6.1",
                version="build",
                machine="armv7l",
                processor="",
            ),
            cpu_count_fn=lambda: 4,
            pointer_bits=32,
        )
        self.assertEqual(result["hardware"]["board"]["revision"], "a02082")

    def test_default_runner_uses_and_cleans_disposable_gstreamer_registry(self) -> None:
        registry_paths: list[Path] = []

        def fake_run(argv: list[str], **kwargs: object) -> SimpleNamespace:
            if argv[0].startswith("gst-"):
                env = kwargs["env"]
                assert isinstance(env, dict)
                registry = Path(env["GST_REGISTRY"])
                self.assertEqual(env["GST_REGISTRY_1_0"], str(registry))
                self.assertNotIn("GST_REGISTRY_UPDATE", env)
                self.assertNotIn("GST_REGISTRY_DISABLE", env)
                registry.write_text("temporary cache", encoding="utf-8")
                registry_paths.append(registry)
            return SimpleNamespace(returncode=1, stdout="", stderr="unavailable")

        original_environment = os.environ.copy()
        with mock.patch.dict(os.environ, original_environment, clear=True):
            for name in (
                "GST_REGISTRY",
                "GST_REGISTRY_1_0",
                "GST_REGISTRY_DISABLE",
                "GST_REGISTRY_UPDATE",
            ):
                os.environ.pop(name, None)
            expected_environment = os.environ.copy()
            with mock.patch.object(probe.subprocess, "run", side_effect=fake_run):
                result = probe.collect_probe(
                    reader=pi_files().get,
                    disk_usage_fn=lambda _path: (100, 20, 80),
                    uname_fn=lambda: SimpleNamespace(
                        system="Linux", release="6.1", machine="armv6l", processor=""
                    ),
                    cpu_count_fn=lambda: 1,
                    pointer_bits=32,
                )
            self.assertEqual(os.environ, expected_environment)

        self.assertTrue(registry_paths)
        self.assertEqual(len(set(registry_paths)), 1)
        self.assertFalse(registry_paths[0].exists())
        self.assertFalse(result["gstreamer"]["registry_update_disabled"])
        self.assertEqual(
            result["actions"], probe._actions(json.loads(probe.render_json(result)))
        )

    def test_default_runner_preserves_explicit_gstreamer_registry(self) -> None:
        seen_registries: list[str] = []

        def fake_run(argv: list[str], **kwargs: object) -> SimpleNamespace:
            if argv[0].startswith("gst-"):
                env = kwargs["env"]
                assert isinstance(env, dict)
                seen_registries.append(env["GST_REGISTRY"])
                self.assertEqual(env["GST_REGISTRY_UPDATE"], "no")
            return SimpleNamespace(returncode=1, stdout="", stderr="unavailable")

        with tempfile.TemporaryDirectory() as directory:
            registry = Path(directory) / "explicit.bin"
            registry.write_text("user cache", encoding="utf-8")
            environment = os.environ.copy()
            environment.pop("GST_REGISTRY_1_0", None)
            environment["GST_REGISTRY"] = str(registry)
            with mock.patch.dict(os.environ, environment, clear=True):
                expected_environment = os.environ.copy()
                with mock.patch.object(probe.subprocess, "run", side_effect=fake_run):
                    result = probe.collect_probe(
                        reader=pi_files().get,
                        disk_usage_fn=lambda _path: (100, 20, 80),
                        uname_fn=lambda: SimpleNamespace(
                            system="Linux", release="6.1", machine="armv6l", processor=""
                        ),
                        cpu_count_fn=lambda: 1,
                        pointer_bits=32,
                    )
                self.assertEqual(os.environ, expected_environment)
            self.assertEqual(registry.read_text(encoding="utf-8"), "user cache")

        self.assertTrue(seen_registries)
        self.assertEqual(set(seen_registries), {str(registry)})
        self.assertTrue(result["gstreamer"]["registry_update_disabled"])


class OutputTests(unittest.TestCase):
    def test_json_cli_emits_schema_v1_to_stdout(self) -> None:
        stdout = io.StringIO()
        with contextlib.redirect_stdout(stdout):
            returncode = probe.main(["--format", "json"], collect=collect_pi)
        decoded = json.loads(stdout.getvalue())
        self.assertEqual(returncode, 0)
        self.assertEqual(decoded["schema_version"], 1)
        self.assertEqual(decoded["status"], "present")
        self.assertLess(stdout.getvalue().index('"actions"'), stdout.getvalue().index('"audio"'))

    def test_json_cli_emits_result_and_returns_nonzero_when_preflight_is_not_ready(self) -> None:
        missing = collect_pi(complete_runner(missing_element="srtsink"))
        unverified_runner = complete_runner()
        del unverified_runner.responses[("getconf", "LONG_BIT")]
        unverified = collect_pi(unverified_runner)

        for expected_status, result in (
            (probe.MISSING, missing),
            (probe.UNVERIFIED, unverified),
        ):
            with self.subTest(expected_status):
                stdout = io.StringIO()
                with contextlib.redirect_stdout(stdout):
                    returncode = probe.main(
                        ["--format", "json"], collect=lambda result=result: result
                    )
                self.assertEqual(returncode, 1)
                self.assertEqual(json.loads(stdout.getvalue())["status"], expected_status)

    def test_human_output_is_actionable(self) -> None:
        result = collect_pi(complete_runner(missing_element="srtsink"))
        rendered = probe.render_human(result)
        self.assertIn("Overall: MISSING", rendered)
        self.assertIn("Required GStreamer elements: MISSING", rendered)
        self.assertIn("Actions:", rendered)
        self.assertIn("gstreamer1.0-plugins-bad (srtsink)", rendered)

    def test_human_output_accepts_pre_gate_schema_v1_pi_artifact(self) -> None:
        result = collect_pi()
        del result["platform"]["os_architecture_baseline"]
        rendered = probe.render_human(result)
        self.assertIn("Overall: PRESENT", rendered)
        self.assertIn("Supported OS/architecture baseline: PRESENT", rendered)


if __name__ == "__main__":
    unittest.main()
