# Type Path                                  Mode User                Group                   Age Argument
d /etc/tinypirelay                          0755 root                root                    -   -
d /etc/tinypirelay/media                    0700 tinypirelay-media   tinypirelay-media       -   -
d /etc/tinypirelay/web                      0700 tinypirelay-web     tinypirelay-web         -   -
d /run/tinypirelay                          0750 tinypirelay-media   tinypirelay-control     -   -
d /run/tinypirelay-maintenance              0750 root                tinypirelay-web         -   -
f /run/lock/tinypirelay-installer.lock       0600 root                root                    -   -
d /var/cache/tinypirelay-media              0750 tinypirelay-media   tinypirelay-media       -   -
d /var/lib/tinypirelay                      0710 root                tinypirelay-control     -   -
d /var/lib/tinypirelay/recordings           0750 tinypirelay-media   tinypirelay-media       -   -
d /var/lib/tinypirelay/backups              0700 root                root                    -   -
